heat_template_version: 2018-08-31

parameters:
    ansible_version:
        type: string
        default: ""

    inventory:
        description: >
            The content of this variable will be written in /inventory
            and used by ansible.
        type: string
        default: ""

    inventory_paths:
        description: >
            These paths (and `/inventory`) will be used by ansible as
            inventories.
        type: json
        default:
        -   /dev/null

    playbook:
        description: >
            The content of this variable will be written in /playbook.yml.
        type: string
        default: ""

    playbook_name:
        description: >
            The path (possibly relative to the repository url) of the
            playbook which will be executed.
        type: string
        default: /playbook.yml

    cache_volume_path:
        description: >
            The path of the block device used to cache repository and
            virtualenv
        type: string
        default: /dev/sdb

    repository_url:
        type: string
        default: ""

    repository_version:
        type: string
        default: master

    repository_force:
        type: boolean
        default: yes

    flavor:
        type: string
        default: sys.2c2r

    image:
        type: string

    hostname:
        type: string

    network:
        type: string
        default: template-os

    ansible_playbook_args:
        type: string
        default: "-e ansible_become=yes -e ansible_user=debian --ssh-common-args='-o StrictHostKeyChecking=no'"

    ssh_key:
        type: string

    ansible_wait_for_connection:
        type: boolean
        default: yes

    cache_type:
        type: string
        default: ceph

    requirements_txt:
        type: string
        default: requirements.txt

resources:
    cache_volume:
        type: OS::Cinder::Volume
        properties:
            volume_type: {get_param: cache_type}
            size: 10

    security_group:
        type: OS::Neutron::SecurityGroup
        properties:
            rules:
            -   protocol: tcp
                port_range_min: 22
                port_range_max: 22
            -   protocol: icmp

    port:
        type: OS::Neutron::Port
        properties:
            network: {get_param: network}
            security_groups:
            -   {get_resource: security_group}

    server:
        type: OS::Nova::Server
        properties:
            flavor: {get_param: flavor}
            name: {get_param: hostname}
            block_device_mapping_v2:
            -   image_id: {get_param: image}
                delete_on_termination: yes
                volume_size: 10
            networks:
            -   port: {get_resource: port}
            user_data_format: RAW
            user_data: {get_resource: write_inventory_and_playbook}

    cache_volume_attachment:
        type: OS::Cinder::VolumeAttachment
        properties:
            instance_uuid: {get_resource: server}
            volume_id: {get_resource: cache_volume}

    ansible_runner_script:
        type: OS::Heat::Value
        properties:
            value:
                str_replace:
                    params:
                        $ansible_version: {get_param: ansible_version}
                        $repository_url: {get_param: repository_url}
                        $repository_version: {get_param: repository_version}
                        $playbook_args: {get_param: ansible_playbook_args}
                        $playbook_name: {get_param: playbook_name}
                        $ansible_wait_for_connection: {get_param: ansible_wait_for_connection}
                        $ssh_key: {get_param: ssh_key}
                        $requirements_txt: {get_param: requirements_txt}
                        $cache_volume_path: {get_param: cache_volume_path}
                        $inventory_param:
                            list_join:
                            -   " "
                            -   repeat:
                                    for_each:
                                        $inventory_path:
                                            list_concat:
                                            -   -   /inventory
                                            -   {get_param: inventory_paths}
                                    template: "-i $inventory_path"
                    template: |
                        #!/bin/bash
                        set -x
                        set -e
                        
                        mkdir -p /root/.ssh
                        chmod 700 /root/.ssh
                        echo "$ssh_key" > /root/.ssh/id_rsa
                        chmod 600 /root/.ssh/id_rsa
                        
                        while ! [ -b $cache_volume_path ]; do echo "waiting for $cache_volume_path"; sleep 1;done
                        blkid -o full $cache_volume_path | grep ext4 || mkfs.ext4 "$cache_volume_path"
                        if ! [ -d /cache/ ]; then mkdir /cache; fi
                        
                        if ! grep "^$cache_volume_path" /etc/mtab; then
                        cat >> /etc/fstab <<EOF
                        #ansible_runner
                        $cache_volume_path /cache ext4 auto,defaults 0 0
                        #end ansible runner
                        EOF
                        mount /cache
                        fi
                        
                        apt update
                        apt install -y python3 python3-pip git virtualenv
                        virtualenv -p python3 /cache/venv || true
                        . /cache/venv/bin/activate
                        pip3 install ansible$ansible_version
                        
                        cd /cache
                        if ! [ -z "$repository_url" ]; then
                            ansible-playbook -i localhost, /prepare_local_repository.yml
                            cd /cache/repo
                            if ! [ -z "$requirements_txt" ] && [ -e $requirements_txt ]; then
                                pip install -r $requirements_txt
                            fi
                        fi
                        
                        if [ "$ansible_wait_for_connection" = "True" ]; then
                            ansible $playbook_args $inventory_param -m wait_for_connection all,localhost
                        fi
                        ansible-playbook $playbook_args $inventory_param "$playbook_name"

    prepare_local_repository:
        type: OS::Heat::Value
        properties:
            value:
                str_replace:
                    params:
                        $repository_url: {get_param: repository_url}
                        $repository_version: {get_param: repository_version}
                        $repository_force: {get_param: repository_force}
                    template: |
                        -   hosts: localhost
                            connection: local
                            gather_facts: no
                            tasks:
                            -   when: |
                                    "$repository_url" != ""
                                git:
                                    repo: "$repository_url"
                                    version: "$repository_version"
                                    dest: /cache/repo/
                                    force: $repository_force

    systemd_unit:
        type: OS::Heat::Value
        properties:
            value: |
                [Unit]
                Description=Ansible runner
                After=network-online.target
                Wants=network-online.target
                [Service]
                Type=OneShot
                RemainAfterExit=True
                ExecStart=/usr/local/bin/ansible_runner
                [Install]
                WantedBy=multi-user.target

    write_inventory_and_playbook:
        type: OS::Heat::CloudConfig
        properties:
            cloud_config:
                write_files:
                -   path: /inventory
                    content: {get_param: inventory}
                -   path: /playbook.yml
                    content: {get_param: playbook}
                -   path: /usr/local/bin/ansible_runner
                    content: {get_attr: [ansible_runner_script, value]}
                    permissions: '0755'
                -   path: /prepare_local_repository.yml
                    content: {get_attr: [prepare_local_repository, value]}
                -   path: /etc/systemd/system/ansible_runner.service
                    content: {get_attr: [systemd_unit, value]}
                runcmd:
                -   systemctl daemon-reload
                -   systemctl enable ansible_runner
                -   systemctl start ansible_runner

outputs:
    test:
        value:
            list_join:
            -   " "
            -   repeat:
                    for_each:
                        $inventory_path:
                            list_concat:
                            -   -   /inventory
                            -   {get_param: inventory_paths}
                    template: "-i $inventory_path"
